the line number of the yaml file is displayed in the error message
nomad-coe/nomad-parser-nexus pull request #34
Opened 2022-08-31 15:08 UTC by aalbino2

2022-09-05 13:12 UTC, aalbino2 commented
I also added the support to "extends" in the yaml file, as aske by @domna 

Note that I also changed the file used for testing:
/nomad/dependencies/parsers/nexus/tests/data/tools/dataconverter/readers/mpes/Ref_nexus_mpes.log

Because some field was changed in the nxdl from recommended or required to optional.

2022-09-05 13:24 UTC, domna approved these changes
The extends keyword works like a charm. Did not review anything else.

The Ref log output for mpes should be the same as in the main branch now, because I updated it only yesterday.

2022-09-06 16:47 UTC, sanbrock requested changes
it would be great to have some test cases where the new feature is checked

2022-09-07 12:33 UTC, shabihsherjeel commented on nexusparser/tools/yaml2nxdl/yaml2nxdl.py
>          del yml_appdef['category']
This line and line no: 111 can be removed out of the two if statements. It is always called  anyways.

2022-09-07 13:28 UTC, shabihsherjeel requested changes

2022-09-07 13:28 UTC, shabihsherjeel commented on nexusparser/tools/yaml2nxdl/yaml2nxdl_forward_tools.py
>          else:
This else could be removed.

2022-09-07 15:00 UTC, shabihsherjeel approved these changes

2022-09-07 15:53 UTC, sanbrock approved these changes

2022-09-07 15:53 UTC, merged