Nyaml2nxdl comment preservation
nomad-coe/nomad-parser-nexus pull request #86
Opened 2023-04-06 08:25 UTC by RubelMozumder

The converter `nyaml2nxdl` can now store comments in forward and backward conversion.

One extra class `XMLComment` has already been, albeit it's been not used(instead XML library was exploited), still, it can be used if needed in the future.

2023-04-06 11:16 UTC, shabihsherjeel requested changes

2023-04-06 11:16 UTC, shabihsherjeel commented on nexusutils/nyaml2nxdl/nyaml2nxdl.py
>              pass
Is this needed?

2023-04-06 11:16 UTC, shabihsherjeel commented on nexusutils/nyaml2nxdl/nyaml2nxdl_backward_tools.py
> +        # pi -> ProcessInstructio section
Can be removed.

2023-04-06 11:16 UTC, shabihsherjeel commented on nexusutils/nyaml2nxdl/nyaml2nxdl_backward_tools.py
> +        # xml_tree = {'tree': tree.getroot(), 'node': tree.getroot()}
Not needed.

2023-04-06 11:16 UTC, shabihsherjeel commented on nexusutils/nyaml2nxdl/nyaml2nxdl_backward_tools.py
> +    def strore_root_level_comments(self, holder, comment):
typo. "store"

2023-04-19 19:43 UTC, RubelMozumder reviewed
Done!

2023-04-20 15:56 UTC, sanbrock commented on nexusutils/nyaml2nxdl/comment_collector.py
> +                        # Line number in file starts from 1
Well, `line_num` as yielded by `enumerate(lines)` in line 89 normally starts with the value of 0.

2023-04-20 22:02 UTC, sanbrock approved these changes
LGTM

2023-04-20 22:04 UTC, merged